# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }:
[
  (fetchNuGet {
    pname = "ClangSharp";
    version = "18.1.0";
    hash = "sha256-ggWWS6ONcjH7TmD8kO0RbWUVVrm1LgowHzi3bGOge38=";
  })
  (fetchNuGet {
    pname = "ClangSharp.Interop";
    version = "18.1.0";
    hash = "sha256-RQ6ngH9JlWYFljCJJ1eEea8hln07uoCyGXRKa4H2Dp0=";
  })
  (fetchNuGet {
    pname = "ClangSharp.PInvokeGenerator";
    version = "18.1.0";
    hash = "sha256-pASpO9N/KgX36/R+8fbRPzsq49nohheBDRL99YBuzlk=";
  })
  (fetchNuGet {
    pname = "libclang";
    version = "18.1.3.2";
    hash = "sha256-/j/+jkBtn+byQv8BQR9D1nArbRYO4iFe32nUd3y4mq4=";
  })
  (fetchNuGet {
    pname = "libclang.runtime.linux-arm64";
    version = "18.1.3.2";
    hash = "sha256-VqY346TTEDNYN9u1A3fex3pF2NWLE0DQu4s6RE7MC3s=";
  })
  (fetchNuGet {
    pname = "libclang.runtime.linux-x64";
    version = "18.1.3.2";
    hash = "sha256-GSWOM8LnhcWeaux9mFGTik4sDE/yfSqHj0OokMLC004=";
  })
  (fetchNuGet {
    pname = "libclang.runtime.osx-arm64";
    version = "18.1.3";
    hash = "sha256-lB15ba8zJcp67NZ6tgWY+eZIDePiwAx8uJYu5u/0fyg=";
  })
  (fetchNuGet {
    pname = "libclang.runtime.osx-x64";
    version = "18.1.3";
    hash = "sha256-XwBmJqd0Dyu2nm2HYo5qVqwMLlX5Amy2xrfVETUfU/w=";
  })
  (fetchNuGet {
    pname = "libClangSharp";
    version = "18.1.3.1";
    hash = "sha256-q2C27wOOQtnV6Gi4PAkCTg0TKQzOLxZj9BDSjHI5Rk0=";
  })
  (fetchNuGet {
    pname = "libClangSharp.runtime.linux-arm64";
    version = "18.1.3.1";
    hash = "sha256-LqWHGnXBojuaEI6GG4op7gg7L0jaiLMnMyftiQEAogY=";
  })
  (fetchNuGet {
    pname = "libClangSharp.runtime.linux-x64";
    version = "18.1.3.1";
    hash = "sha256-aOl/4qi95618ZcVFsyDe7J4w8iI1+VpdNfj3yJVwleQ=";
  })
  (fetchNuGet {
    pname = "libClangSharp.runtime.osx-arm64";
    version = "18.1.3.1";
    hash = "sha256-OwVL86jQAjHfBWjZFLVh2EvFPt60oIDz3642UiLfJYI=";
  })
  (fetchNuGet {
    pname = "libClangSharp.runtime.osx-x64";
    version = "18.1.3.1";
    hash = "sha256-TDcLG63Ems41pKKnoa6bp1zSSNriXOBRrWILxsVL+NQ=";
  })
  (fetchNuGet {
    pname = "Microsoft.Build.Framework";
    version = "17.10.4";
    hash = "sha256-J9N2VDoyd2P0e4PLhI3XsYsiyE0vKSIerhglV0FW+Bk=";
  })
  (fetchNuGet {
    pname = "Microsoft.Build.Utilities.Core";
    version = "17.10.4";
    hash = "sha256-eHEObY1YqK/+hOJmUzSu7u/dKp/OX5qQOWk07rEUReQ=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.Analyzers";
    version = "3.3.4";
    hash = "sha256-qDzTfZBSCvAUu9gzq2k+LOvh6/eRvJ9++VCNck/ZpnE=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.Common";
    version = "4.8.0";
    hash = "sha256-3IEinVTZq6/aajMVA8XTRO3LTIEt0PuhGyITGJLtqz4=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.CSharp";
    version = "4.8.0";
    hash = "sha256-MmOnXJvd/ezs5UPcqyGLnbZz5m+VedpRfB+kFZeeqkU=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.ResxSourceGenerator";
    version = "3.11.0-beta1.24324.1";
    hash = "sha256-+YEdFt4em1e8SMC3PnRAwOfyMZLwWPJo7/loTt7l9kQ=";
  })
  (fetchNuGet {
    pname = "Microsoft.NET.StringTools";
    version = "17.10.4";
    hash = "sha256-nXY7YaIx6sXn7aMqpF4bW4d2J5U1KNb9sXqRSd8MpOc=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "1.1.0";
    hash = "sha256-FeM40ktcObQJk4nMYShB61H/E8B7tIKfl9ObJ0IOcCM=";
  })
  (fetchNuGet {
    pname = "NETStandard.Library";
    version = "2.0.3";
    hash = "sha256-Prh2RPebz/s8AzHb2sPHg3Jl8s31inv9k+Qxd293ybo=";
  })
  (fetchNuGet {
    pname = "System.Buffers";
    version = "4.5.1";
    hash = "sha256-wws90sfi9M7kuCPWkv1CEYMJtCqx9QB/kj0ymlsNaxI=";
  })
  (fetchNuGet {
    pname = "System.Collections.Immutable";
    version = "7.0.0";
    hash = "sha256-9an2wbxue2qrtugYES9awshQg+KfJqajhnhs45kQIdk=";
  })
  (fetchNuGet {
    pname = "System.Collections.Immutable";
    version = "8.0.0";
    hash = "sha256-F7OVjKNwpqbUh8lTidbqJWYi476nsq9n+6k0+QVRo3w=";
  })
  (fetchNuGet {
    pname = "System.CommandLine";
    version = "2.0.0-beta4.24209.3";
    hash = "sha256-u2jJfGip9LyWJop5qUgQxUvnnXI3AETLuarrmE6zhEw=";
    url = "https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/516521bf-6417-457e-9a9c-0a4bdfde03e7/nuget/v3/flat2/system.commandline/2.0.0-beta4.24209.3/system.commandline.2.0.0-beta4.24209.3.nupkg";
  })
  (fetchNuGet {
    pname = "System.Configuration.ConfigurationManager";
    version = "8.0.0";
    hash = "sha256-xhljqSkNQk8DMkEOBSYnn9lzCSEDDq4yO910itptqiE=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.EventLog";
    version = "8.0.0";
    hash = "sha256-rt8xc3kddpQY4HEdghlBeOK4gdw5yIj4mcZhAVtk2/Y=";
  })
  (fetchNuGet {
    pname = "System.Memory";
    version = "4.5.5";
    hash = "sha256-EPQ9o1Kin7KzGI5O3U3PUQAZTItSbk9h/i4rViN3WiI=";
  })
  (fetchNuGet {
    pname = "System.Numerics.Vectors";
    version = "4.4.0";
    hash = "sha256-auXQK2flL/JpnB/rEcAcUm4vYMCYMEMiWOCAlIaqu2U=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Metadata";
    version = "7.0.0";
    hash = "sha256-GwAKQhkhPBYTqmRdG9c9taqrKSKDwyUgOEhWLKxWNPI=";
  })
  (fetchNuGet {
    pname = "System.Runtime.CompilerServices.Unsafe";
    version = "6.0.0";
    hash = "sha256-bEG1PnDp7uKYz/OgLOWs3RWwQSVYm+AnPwVmAmcgp2I=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.ProtectedData";
    version = "8.0.0";
    hash = "sha256-fb0pa9sQxN+mr0vnXg1Igbx49CaOqS+GDkTfWNboUvs=";
  })
  (fetchNuGet {
    pname = "System.Text.Encoding.CodePages";
    version = "7.0.0";
    hash = "sha256-eCKTVwumD051ZEcoJcDVRGnIGAsEvKpfH3ydKluHxmo=";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks.Extensions";
    version = "4.5.4";
    hash = "sha256-owSpY8wHlsUXn5xrfYAiu847L6fAKethlvYx97Ri1ng=";
  })
]
