# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }: [
  (fetchNuGet { pname = "Godot.NET.Sdk"; version = "4.2.2"; hash = "sha256-H/MPBAuJfiehRONhlNfdaTZggVyS6MzpF2TJLa9uNA4="; })
  (fetchNuGet { pname = "Godot.SourceGenerators"; version = "4.2.2"; hash = "sha256-B6bP/RaPDlIj18fqSIxpqSR73DZxRcNECu1kq4Rbu+8="; })
  (fetchNuGet { pname = "GodotSharp"; version = "4.2.2"; hash = "sha256-p+PPW3betIIquPEZuwuWfCSliVg+52VV5UR8m/kFKy0="; })
  (fetchNuGet { pname = "GodotSharpEditor"; version = "4.2.2"; hash = "sha256-jHSQIpRsMugA0NwM/xlLLoUVKTF4BzNrZBMg7NSySu8="; })
]
